version: '3'

services:
      
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
        MYSQL_DATABASE: enti
        MYSQL_ROOT_PASSWORD: local
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
      - ./mysql/configs:/etc/mysql/conf.d
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www
    ports:
      - '9000:9000'
    networks:
      - app-network
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - '3001:80'
    volumes:
      - /sessions
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

